\ !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
\ automatically generated by mkversion.sh shell script!
\ !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#75 variable version-revision
0 0 2variable version-rev
0 0 2variable version-id
0 0 2variable version-date

: __set_version_stuff  
  s" 75+"             version-rev  2!
  s" af22db873bea+"   version-id   2! 
  s" 2016-09-21"      version-date 2!
;
__set_version_stuff

