 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 
 \ automatically generated by mkversion.sh shell script!
 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

    
 \ \ \ \ integer version number
#96 variable version-revision

 \ \ \ \ string varient of version number
0 0 2variable version-rev

 \ \ \ \ string version id - revision hash
0 0 2variable version-id

 \ \ \ \ string date in YYYY-MM-DD format
0 0 2variable version-date

: __set_version_stuff  
  s" 96"             version-rev  2!
  s" 8cab66a77277"   version-id   2! 
  s" 2016-11-21"      version-date 2!
;
__set_version_stuff

