 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 
 \ automatically generated by mkversion.sh shell script!
 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 

    
 \ \ \ \ integer version number
#87 variable version-revision

 \ \ \ \ string varient of version number
0 0 2variable version-rev

 \ \ \ \ string version id - revision hash
0 0 2variable version-id

 \ \ \ \ string date in YYYY-MM-DD format
0 0 2variable version-date

: __set_version_stuff  
  s" 87"             version-rev  2!
  s" f32800afd6a0"   version-id   2! 
  s" 2016-10-30"      version-date 2!
;
__set_version_stuff

