#!/bin/sh

VERS=$(hg id -n)
ID=$(hg id -i)
TSTAMP=$(date +%Y-%m-%d)

if  echo $ID | grep '+' >/dev/null; then
    echo WARNING! uncommited changes 
#    exit 1
fi

cat > version.fs <<EOF
\ !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
\ automatically generated by mkversion.sh shell script!
\ !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#$(echo ${VERS}|sed -e 's/+$//') variable version-revision
0 0 2variable version-rev
0 0 2variable version-id
0 0 2variable version-date

: __set_version_stuff  
  s" ${VERS}"             version-rev  2!
  s" ${ID}"   version-id   2! 
  s" ${TSTAMP}"      version-date 2!
;
__set_version_stuff

EOF
